services:
  app:
    image: ${DOCKER_IMAGE:-afkerahmed/lead-management-app:latest}
    build:
      context: ../
      args:
        NEXT_PUBLIC_POCKETBASE_URL: ${NEXT_PUBLIC_POCKETBASE_URL}
    container_name: lead-management-app
    ports:
      - "${APP_PORT:-8082}:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=${NEXT_PUBLIC_POCKETBASE_URL}
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      - NODE_ENV=production
    restart: unless-stopped
